<?php

return array (
  0 => 
  array (
    'name' => 'Angel Lung-ay Aday',
    'email' => '25-10194@aldersgate.edu.ph',
    'id_number' => '25-10194',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '3062',
  ),
  1 => 
  array (
    'name' => 'Steven Dane Dela Cruz Agustin',
    'email' => '25-10269@aldersgate.edu.ph',
    'id_number' => '25-10269',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '2191',
  ),
  2 => 
  array (
    'name' => 'John Luis Caigoy Alcober',
    'email' => '25-10217@aldersgate.edu.ph',
    'id_number' => '25-10217',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '4962',
  ),
  3 => 
  array (
    'name' => 'Bianca Irish Cinco Antolin',
    'email' => '25-10113@aldersgate.edu.ph',
    'id_number' => '25-10113',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '6798',
  ),
  4 => 
  array (
    'name' => 'Daren **** Aquino',
    'email' => '24-10348@aldersgate.edu.ph',
    'id_number' => '24-10348',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-2A',
    'password' => '3283',
  ),
  5 => 
  array (
    'name' => 'Janiel John Ila Arconeda',
    'email' => '25-10086@aldersgate.edu.ph',
    'id_number' => '25-10086',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '4471',
  ),
  6 => 
  array (
    'name' => 'Caryl Bacani',
    'email' => '25-10063@aldersgate.edu.ph',
    'id_number' => '25-10063',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '7963',
  ),
  7 => 
  array (
    'name' => 'Jasmine Janika Tigno Bajo',
    'email' => '25-10315@aldersgate.edu.ph',
    'id_number' => '25-10315',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '2511',
  ),
  8 => 
  array (
    'name' => 'Kian Ralf Dumulag Balinon',
    'email' => '22-10008@aldersgate.edu.ph',
    'id_number' => '22-10008',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '6176',
  ),
  9 => 
  array (
    'name' => 'Jaymar Balicana Baltazar',
    'email' => '019-0008@aldersgate.edu.ph',
    'id_number' => '019-0008',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '3546',
  ),
  10 => 
  array (
    'name' => 'Lye Manuel Bandolin',
    'email' => '25-10051@aldersgate.edu.ph',
    'id_number' => '25-10051',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '5171',
  ),
  11 => 
  array (
    'name' => 'Roelito Jr. Evangelista Bersamin',
    'email' => '25-10336@aldersgate.edu.ph',
    'id_number' => '25-10336',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '1786',
  ),
  12 => 
  array (
    'name' => 'Joana Grace Bedaña Bigao',
    'email' => '25-10365@aldersgate.edu.ph',
    'id_number' => '25-10365',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '4743',
  ),
  13 => 
  array (
    'name' => 'Aaron Paul Marzan Bueno',
    'email' => '25-10250@aldersgate.edu.ph',
    'id_number' => '25-10250',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '9690',
  ),
  14 => 
  array (
    'name' => 'Valiant Dave Inhumang Bumanghat',
    'email' => '25-10324@aldersgate.edu.ph',
    'id_number' => '25-10324',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '9287',
  ),
  15 => 
  array (
    'name' => 'Corraine Zaina Quintero Cabanban',
    'email' => '25-10478@aldersgate.edu.ph',
    'id_number' => '25-10478',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '4849',
  ),
  16 => 
  array (
    'name' => 'Ron John Labog Cabanilla',
    'email' => '25-10187@aldersgate.edu.ph',
    'id_number' => '25-10187',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '4800',
  ),
  17 => 
  array (
    'name' => 'Marniña Dela Cruz Cablayan',
    'email' => '24-20091@aldersgate.edu.ph',
    'id_number' => '24-20091',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '3647',
  ),
  18 => 
  array (
    'name' => 'Jan Carlo Dela Cruz Cada',
    'email' => '25-10281@aldersgate.edu.ph',
    'id_number' => '25-10281',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '0182',
  ),
  19 => 
  array (
    'name' => 'Justine Carl Mamaril Castro',
    'email' => '25-10253@aldersgate.edu.ph',
    'id_number' => '25-10253',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '0747',
  ),
  20 => 
  array (
    'name' => 'Jeremaiah Bahingawan Concepcion',
    'email' => '25-10244@aldersgate.edu.ph',
    'id_number' => '25-10244',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '6657',
  ),
  21 => 
  array (
    'name' => 'Glaiza Mae Doles Corpuz',
    'email' => 'sy230013@aldersgate.edu.ph',
    'id_number' => 'SY230013',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '4133',
  ),
  22 => 
  array (
    'name' => 'Mark Chester Monar Corpuz',
    'email' => '25-10414@aldersgate.edu.ph',
    'id_number' => '25-10414',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '9253',
  ),
  23 => 
  array (
    'name' => 'Maureen Karylle Cunanan',
    'email' => '25-10087@aldersgate.edu.ph',
    'id_number' => '25-10087',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '4833',
  ),
  24 => 
  array (
    'name' => 'Kerby Ozar Dandin',
    'email' => '25-10310@aldersgate.edu.ph',
    'id_number' => '25-10310',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '1050',
  ),
  25 => 
  array (
    'name' => 'Darell Caddawan Dapiawen',
    'email' => '25-10525@aldersgate.edu.ph',
    'id_number' => '25-10525',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '7037',
  ),
  26 => 
  array (
    'name' => 'Jhon Levie Labog David',
    'email' => '25-10133@aldersgate.edu.ph',
    'id_number' => '25-10133',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '0183',
  ),
  27 => 
  array (
    'name' => 'Gerwyn Ryan Gallo De Lumen',
    'email' => '25-10169@aldersgate.edu.ph',
    'id_number' => '25-10169',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '4359',
  ),
  28 => 
  array (
    'name' => 'Princess Elaine Barotillo Delos Santos',
    'email' => '25-10096@aldersgate.edu.ph',
    'id_number' => '25-10096',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '9818',
  ),
  29 => 
  array (
    'name' => 'April Joy Desiar',
    'email' => '019-0052@aldersgate.edu.ph',
    'id_number' => '019-0052',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '3096',
  ),
  30 => 
  array (
    'name' => 'Jhundle Mark Jezz Banagan Dizon',
    'email' => '25-10081@aldersgate.edu.ph',
    'id_number' => '25-10081',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '1657',
  ),
  31 => 
  array (
    'name' => 'Lebron James Leorin Domingo',
    'email' => '25-10066@aldersgate.edu.ph',
    'id_number' => '25-10066',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '7801',
  ),
  32 => 
  array (
    'name' => 'Carl Raven Boac Esperon',
    'email' => '25-10303@aldersgate.edu.ph',
    'id_number' => '25-10303',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '4405',
  ),
  33 => 
  array (
    'name' => 'Yves Clint Sagun Espiritu',
    'email' => '25-10518@aldersgate.edu.ph',
    'id_number' => '25-10518',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '2511',
  ),
  34 => 
  array (
    'name' => 'Clint John Dominic Lazo Esquivel',
    'email' => '24-20104@aldersgate.edu.ph',
    'id_number' => '24-20104',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '2710',
  ),
  35 => 
  array (
    'name' => 'Feliz John Bumanlag Fabian',
    'email' => '21-10732@aldersgate.edu.ph',
    'id_number' => '21-10732',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-2A',
    'password' => '1176',
  ),
  36 => 
  array (
    'name' => 'Mirasol Palasi Gaddingan',
    'email' => '25-10182@aldersgate.edu.ph',
    'id_number' => '25-10182',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '3687',
  ),
  37 => 
  array (
    'name' => 'Trendz Galutera',
    'email' => '25-10376@aldersgate.edu.ph',
    'id_number' => '25-10376',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '7334',
  ),
  38 => 
  array (
    'name' => 'Jeremia Ruma Garcia',
    'email' => '25-10362@aldersgate.edu.ph',
    'id_number' => '25-10362',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '3248',
  ),
  39 => 
  array (
    'name' => 'Andrei Linus Agravante **** Gonzales',
    'email' => '23-0526@aldersgate.edu.ph',
    'id_number' => '23-0526',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '0100',
  ),
  40 => 
  array (
    'name' => 'Mark Angelo De Vera Gutierez',
    'email' => '25-10266@aldersgate.edu.ph',
    'id_number' => '25-10266',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '5007',
  ),
  41 => 
  array (
    'name' => 'Brendon Aldred Ruiz Hull',
    'email' => '25-10428@aldersgate.edu.ph',
    'id_number' => '25-10428',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '8518',
  ),
  42 => 
  array (
    'name' => 'Andrei Dare Jorge',
    'email' => '019-0023@aldersgate.edu.ph',
    'id_number' => '019-0023',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '9707',
  ),
  43 => 
  array (
    'name' => 'Justin Mhar Jorge',
    'email' => '019-0018@aldersgate.edu.ph',
    'id_number' => '019-0018',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '1023',
  ),
  44 => 
  array (
    'name' => 'Nash Cyrille Janvyne Villegas Legaspi',
    'email' => '25-10577@aldersgate.edu.ph',
    'id_number' => '25-10577',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '9983',
  ),
  45 => 
  array (
    'name' => 'Jhervin Vincent Balbole Leopardas',
    'email' => '25-10128@aldersgate.edu.ph',
    'id_number' => '25-10128',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '0677',
  ),
  46 => 
  array (
    'name' => 'Joemar Abbac Lorenzo',
    'email' => '25-10329@aldersgate.edu.ph',
    'id_number' => '25-10329',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '9734',
  ),
  47 => 
  array (
    'name' => 'Jedrick Pedines Magbitang',
    'email' => '25-10004@aldersgate.edu.ph',
    'id_number' => '25-10004',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '4100',
  ),
  48 => 
  array (
    'name' => 'John Mark Lapitan Mallari',
    'email' => '22-10310@aldersgate.edu.ph',
    'id_number' => '22-10310',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '1795',
  ),
  49 => 
  array (
    'name' => 'Enaira Shamine Jannara Mingua Martin',
    'email' => '25-10242@aldersgate.edu.ph',
    'id_number' => '25-10242',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '4166',
  ),
  50 => 
  array (
    'name' => 'Ashley Andres Martinez',
    'email' => '25-10058@aldersgate.edu.ph',
    'id_number' => '25-10058',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '5687',
  ),
  51 => 
  array (
    'name' => 'Brian Narag',
    'email' => '25-10216@aldersgate.edu.ph',
    'id_number' => '25-10216',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '3583',
  ),
  52 => 
  array (
    'name' => 'Marck Kian Nacar Nastor',
    'email' => '25-10325@aldersgate.edu.ph',
    'id_number' => '25-10325',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '8397',
  ),
  53 => 
  array (
    'name' => 'Jhun Dave Lucas Norberte',
    'email' => '25-10276@aldersgate.edu.ph',
    'id_number' => '25-10276',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '0107',
  ),
  54 => 
  array (
    'name' => 'Mary Angelie De Guzman Ongyaco',
    'email' => '25-10132@aldersgate.edu.ph',
    'id_number' => '25-10132',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '0736',
  ),
  55 => 
  array (
    'name' => 'Aren Jhan Acosta Pajarillo',
    'email' => 'sy230020@aldersgate.edu.ph',
    'id_number' => 'SY230020',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '1453',
  ),
  56 => 
  array (
    'name' => 'Frankie Bajar Pamesa',
    'email' => '25-10010@aldersgate.edu.ph',
    'id_number' => '25-10010',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '8385',
  ),
  57 => 
  array (
    'name' => 'Judy Ann Cabalteja Panganiban',
    'email' => '25-10126@aldersgate.edu.ph',
    'id_number' => '25-10126',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '0125',
  ),
  58 => 
  array (
    'name' => 'Cyril Ayne Maraggun Pasion',
    'email' => '25-10346@aldersgate.edu.ph',
    'id_number' => '25-10346',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '1359',
  ),
  59 => 
  array (
    'name' => 'Kriza mae Piñera',
    'email' => '019-0025@aldersgate.edu.ph',
    'id_number' => '019-0025',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '6963',
  ),
  60 => 
  array (
    'name' => 'Jaidelle Jamine Ramos',
    'email' => '018-0187@aldersgate.edu.ph',
    'id_number' => '018-0187',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '1901',
  ),
  61 => 
  array (
    'name' => 'Ian Christopher Panis Recile',
    'email' => '25-10345@aldersgate.edu.ph',
    'id_number' => '25-10345',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '5407',
  ),
  62 => 
  array (
    'name' => 'Ma. Katrina Honrado Refuerzo',
    'email' => '25-10143@aldersgate.edu.ph',
    'id_number' => '25-10143',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '5441',
  ),
  63 => 
  array (
    'name' => 'Kester Cyril Romero',
    'email' => '019-0076@aldersgate.edu.ph',
    'id_number' => '019-0076',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '9491',
  ),
  64 => 
  array (
    'name' => 'Lorainne Jhoy V **** Rosendo',
    'email' => '25-10273@aldersgate.edu.ph',
    'id_number' => '25-10273',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '9938',
  ),
  65 => 
  array (
    'name' => 'Efren Supnad Sabangan',
    'email' => '24-10264@aldersgate.edu.ph',
    'id_number' => '24-10264',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '8405',
  ),
  66 => 
  array (
    'name' => 'Emelyn Tugpi Sairez',
    'email' => '25-10291@aldersgate.edu.ph',
    'id_number' => '25-10291',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '6377',
  ),
  67 => 
  array (
    'name' => 'Gilbert Bacud Salvador',
    'email' => '25-10445@aldersgate.edu.ph',
    'id_number' => '25-10445',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '9142',
  ),
  68 => 
  array (
    'name' => 'Renz Jay Villanueva Santos',
    'email' => '25-10316@aldersgate.edu.ph',
    'id_number' => '25-10316',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '1764',
  ),
  69 => 
  array (
    'name' => 'Tonifer Kurt Pascua Sibunga',
    'email' => '25-10411@aldersgate.edu.ph',
    'id_number' => '25-10411',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '6561',
  ),
  70 => 
  array (
    'name' => 'Kaye Celine Chua Simbala',
    'email' => '25-10030@aldersgate.edu.ph',
    'id_number' => '25-10030',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '7546',
  ),
  71 => 
  array (
    'name' => 'John Marx Galan Sinoy',
    'email' => '25-10166@aldersgate.edu.ph',
    'id_number' => '25-10166',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '9272',
  ),
  72 => 
  array (
    'name' => 'Jian Carlo Beltran Sison',
    'email' => '25-10302@aldersgate.edu.ph',
    'id_number' => '25-10302',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '0436',
  ),
  73 => 
  array (
    'name' => 'Donnabelle Curibang Soto',
    'email' => '25-10052@aldersgate.edu.ph',
    'id_number' => '25-10052',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '4455',
  ),
  74 => 
  array (
    'name' => 'Tracy-anne Joy Echanes Tabita',
    'email' => '25-10357@aldersgate.edu.ph',
    'id_number' => '25-10357',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '5301',
  ),
  75 => 
  array (
    'name' => 'Dawn Trixie Ventura Tallungan',
    'email' => '25-10075@aldersgate.edu.ph',
    'id_number' => '25-10075',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '4486',
  ),
  76 => 
  array (
    'name' => 'Jemicah Tennen Tindungan',
    'email' => '25-10288@aldersgate.edu.ph',
    'id_number' => '25-10288',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '1806',
  ),
  77 => 
  array (
    'name' => 'Merlita Tiam Tobias',
    'email' => '25-10426@aldersgate.edu.ph',
    'id_number' => '25-10426',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '9984',
  ),
  78 => 
  array (
    'name' => 'Rhon Jhervic Bayle Tomines',
    'email' => '25-10300@aldersgate.edu.ph',
    'id_number' => '25-10300',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '6916',
  ),
  79 => 
  array (
    'name' => 'Mary-Lou Tulabing',
    'email' => '25-10347@aldersgate.edu.ph',
    'id_number' => '25-10347',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '0714',
  ),
  80 => 
  array (
    'name' => 'Ronald Leorin Valdez',
    'email' => '25-10067@aldersgate.edu.ph',
    'id_number' => '25-10067',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1A',
    'password' => '5935',
  ),
  81 => 
  array (
    'name' => 'Vince Chrysler Galapon Valdez',
    'email' => '25-10473@aldersgate.edu.ph',
    'id_number' => '25-10473',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '1',
    'section' => 'BSIT-1B',
    'password' => '4929',
  ),
  82 => 
  array (
    'name' => 'Van Hallen Lizardo Angcon',
    'email' => '21-10689@aldersgate.edu.ph',
    'id_number' => '21-10689',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '9630',
  ),
  83 => 
  array (
    'name' => 'Maynard Lizardo Aragon',
    'email' => '016-0057@aldersgate.edu.ph',
    'id_number' => '016-0057',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '5567',
  ),
  84 => 
  array (
    'name' => 'Ron Galam **** Arandia',
    'email' => '24-10337@aldersgate.edu.ph',
    'id_number' => '24-10337',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '6519',
  ),
  85 => 
  array (
    'name' => 'Karl Louie Ralleca Baquiran',
    'email' => '019-0191@aldersgate.edu.ph',
    'id_number' => '019-0191',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '4831',
  ),
  86 => 
  array (
    'name' => 'Jeffrey Dohillo Belandres',
    'email' => '22-10066@aldersgate.edu.ph',
    'id_number' => '22-10066',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '2464',
  ),
  87 => 
  array (
    'name' => 'Ranier Caddawan Bermudez',
    'email' => '24-10449@aldersgate.edu.ph',
    'id_number' => '24-10449',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '3132',
  ),
  88 => 
  array (
    'name' => 'Mary Joy Guiawan Bulan',
    'email' => '24-10088@aldersgate.edu.ph',
    'id_number' => '24-10088',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '9482',
  ),
  89 => 
  array (
    'name' => 'Randelle Jay Serquena Cabarles',
    'email' => '22-10575@aldersgate.edu.ph',
    'id_number' => '22-10575',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '7580',
  ),
  90 => 
  array (
    'name' => 'Jaycee Alindada Cabatic',
    'email' => '24-10027@aldersgate.edu.ph',
    'id_number' => '24-10027',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '5722',
  ),
  91 => 
  array (
    'name' => 'Ryan Miranda Cave',
    'email' => '24-10080@aldersgate.edu.ph',
    'id_number' => '24-10080',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '0795',
  ),
  92 => 
  array (
    'name' => 'Marc Ronniel Banawa Cortes',
    'email' => '018-0135@aldersgate.edu.ph',
    'id_number' => '018-0135',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '5186',
  ),
  93 => 
  array (
    'name' => 'Jesstonie Tuguinay Dawan',
    'email' => '24-10058@aldersgate.edu.ph',
    'id_number' => '24-10058',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '5022',
  ),
  94 => 
  array (
    'name' => 'Nicole Panganiban Dela Cruz',
    'email' => '24-10158@aldersgate.edu.ph',
    'id_number' => '24-10158',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '2296',
  ),
  95 => 
  array (
    'name' => 'Christian Ace Calimag Delfin',
    'email' => '20-10262@aldersgate.edu.ph',
    'id_number' => '20-10262',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-4A',
    'password' => '2651',
  ),
  96 => 
  array (
    'name' => 'John Jr. Dumulag Dogwe',
    'email' => '22-10009@aldersgate.edu.ph',
    'id_number' => '22-10009',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '9564',
  ),
  97 => 
  array (
    'name' => 'Alexander James Lacsamana Escobar',
    'email' => '24-10420@aldersgate.edu.ph',
    'id_number' => '24-10420',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '7460',
  ),
  98 => 
  array (
    'name' => 'Zyron James Lagrata Estrada',
    'email' => '24-10198@aldersgate.edu.ph',
    'id_number' => '24-10198',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '2098',
  ),
  99 => 
  array (
    'name' => 'Kurt Addug Francisco',
    'email' => '22-10296@aldersgate.edu.ph',
    'id_number' => '22-10296',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '0935',
  ),
  100 => 
  array (
    'name' => 'Xiameigh Ballocanag Galera',
    'email' => '20-10336@aldersgate.edu.ph',
    'id_number' => '20-10336',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '6519',
  ),
  101 => 
  array (
    'name' => 'Francis Robert Castillo **** Gecobe',
    'email' => '23-0537@aldersgate.edu.ph',
    'id_number' => '23-0537',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '8405',
  ),
  102 => 
  array (
    'name' => 'Princes Norielle Conde Graganta',
    'email' => '24-10020@aldersgate.edu.ph',
    'id_number' => '24-10020',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '3784',
  ),
  103 => 
  array (
    'name' => 'Zeus Mark Buhang Guieb',
    'email' => '24-10393@aldersgate.edu.ph',
    'id_number' => '24-10393',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '8206',
  ),
  104 => 
  array (
    'name' => 'Joefranze Guimpatan Guinid',
    'email' => '24-10495@aldersgate.edu.ph',
    'id_number' => '24-10495',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '1130',
  ),
  105 => 
  array (
    'name' => 'Marielle Joy Cerezo Gulpani',
    'email' => '24-10003@aldersgate.edu.ph',
    'id_number' => '24-10003',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '8727',
  ),
  106 => 
  array (
    'name' => 'James Panductan Ilarde',
    'email' => '24-10071@aldersgate.edu.ph',
    'id_number' => '24-10071',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '2030',
  ),
  107 => 
  array (
    'name' => 'Trisha Joy Ila Lumicao',
    'email' => '22-10186@aldersgate.edu.ph',
    'id_number' => '22-10186',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '1476',
  ),
  108 => 
  array (
    'name' => 'Julie Nieves Mina Madriaga',
    'email' => '24-10244@aldersgate.edu.ph',
    'id_number' => '24-10244',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '9605',
  ),
  109 => 
  array (
    'name' => 'Karl Russel Mariano',
    'email' => '017-0076@aldersgate.edu.ph',
    'id_number' => '017-0076',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '9295',
  ),
  110 => 
  array (
    'name' => 'Jay Vincent Mariano Mata',
    'email' => '22-10129@aldersgate.edu.ph',
    'id_number' => '22-10129',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '0974',
  ),
  111 => 
  array (
    'name' => 'Christian Prince Angelo Leaño Mendoza',
    'email' => '22-10412@aldersgate.edu.ph',
    'id_number' => '22-10412',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '7330',
  ),
  112 => 
  array (
    'name' => 'Sunshine Concepcion Nasgatan',
    'email' => '018-0189@aldersgate.edu.ph',
    'id_number' => '018-0189',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '5076',
  ),
  113 => 
  array (
    'name' => 'Maria Angela Aggasid Panganiban',
    'email' => '22-10126@aldersgate.edu.ph',
    'id_number' => '22-10126',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '3799',
  ),
  114 => 
  array (
    'name' => 'John Ianmher Pattugalan Policarpio',
    'email' => '24-10108@aldersgate.edu.ph',
    'id_number' => '24-10108',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '4478',
  ),
  115 => 
  array (
    'name' => 'Jeremy Andrada Pontino',
    'email' => '24-10273@aldersgate.edu.ph',
    'id_number' => '24-10273',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '8265',
  ),
  116 => 
  array (
    'name' => 'Jan Angelo Velasco Ret',
    'email' => '24-10002@aldersgate.edu.ph',
    'id_number' => '24-10002',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '5489',
  ),
  117 => 
  array (
    'name' => 'Normandy Perias Ringpis',
    'email' => '20-10815@aldersgate.edu.ph',
    'id_number' => '20-10815',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '2155',
  ),
  118 => 
  array (
    'name' => 'Rica Jane Lamigo Salazar',
    'email' => '24-10001@aldersgate.edu.ph',
    'id_number' => '24-10001',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '9307',
  ),
  119 => 
  array (
    'name' => 'Frances Mariano Silverio',
    'email' => '24-10006@aldersgate.edu.ph',
    'id_number' => '24-10006',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '6340',
  ),
  120 => 
  array (
    'name' => 'Jose Causing Soriano V',
    'email' => '24-10306@aldersgate.edu.ph',
    'id_number' => '24-10306',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '0514',
  ),
  121 => 
  array (
    'name' => 'Adam Judd Valdez',
    'email' => '018-0207@aldersgate.edu.ph',
    'id_number' => '018-0207',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '3258',
  ),
  122 => 
  array (
    'name' => 'Jasmin Bibay Villar',
    'email' => '22-10574@aldersgate.edu.ph',
    'id_number' => '22-10574',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '5605',
  ),
  123 => 
  array (
    'name' => 'Mark Joshua Nepomuceno Yapit',
    'email' => '24-10448@aldersgate.edu.ph',
    'id_number' => '24-10448',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '2',
    'section' => 'BSIT-2A',
    'password' => '9242',
  ),
  124 => 
  array (
    'name' => 'Aaron Layda Acob',
    'email' => '21-10495@aldersgate.edu.ph',
    'id_number' => '21-10495',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '7937',
  ),
  125 => 
  array (
    'name' => 'Jayster Rey Enriquez Cabay',
    'email' => '15-10187@aldersgate.edu.ph',
    'id_number' => '15-10187',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '8171',
  ),
  126 => 
  array (
    'name' => 'John Learry **** Castro',
    'email' => '016-0097@aldersgate.edu.ph',
    'id_number' => '016-0097',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '9423',
  ),
  127 => 
  array (
    'name' => 'Lexter Jay Pinkihan Daulayan',
    'email' => '23-0227@aldersgate.edu.ph',
    'id_number' => '23-0227',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '2958',
  ),
  128 => 
  array (
    'name' => 'Rozalia Jane Dela Cruz Dekket',
    'email' => '23-0072@aldersgate.edu.ph',
    'id_number' => '23-0072',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '6821',
  ),
  129 => 
  array (
    'name' => 'Mark Edrian Dulnuan Garcia',
    'email' => '22-0278@aldersgate.edu.ph',
    'id_number' => '22-0278',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '6708',
  ),
  130 => 
  array (
    'name' => 'Jeon Jero Jac Danao Gragasin',
    'email' => '22-20099@aldersgate.edu.ph',
    'id_number' => '22-20099',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '0677',
  ),
  131 => 
  array (
    'name' => 'Hercules Jon Galanza Honrales',
    'email' => '23-0241@aldersgate.edu.ph',
    'id_number' => '23-0241',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '9905',
  ),
  132 => 
  array (
    'name' => 'Jan Mark Hernandez Manuel',
    'email' => '20-10056@aldersgate.edu.ph',
    'id_number' => '20-10056',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '9656',
  ),
  133 => 
  array (
    'name' => 'John Carlo Pasion Marcelino',
    'email' => '23-0250@aldersgate.edu.ph',
    'id_number' => '23-0250',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '2885',
  ),
  134 => 
  array (
    'name' => 'Kenn Charlee Camba Martinez',
    'email' => '22-0496@aldersgate.edu.ph',
    'id_number' => '22-0496',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '1288',
  ),
  135 => 
  array (
    'name' => 'Jelyn Marcos Monte',
    'email' => '23-0147@aldersgate.edu.ph',
    'id_number' => '23-0147',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '8571',
  ),
  136 => 
  array (
    'name' => 'Melchor Jr. Burgan Paculla',
    'email' => '23-0433@aldersgate.edu.ph',
    'id_number' => '23-0433',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '5448',
  ),
  137 => 
  array (
    'name' => 'Gary Noel Babaran Pascua',
    'email' => '22-10578@aldersgate.edu.ph',
    'id_number' => '22-10578',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '8004',
  ),
  138 => 
  array (
    'name' => 'Gregorio Calanse Ragasa',
    'email' => '016-0128@aldersgate.edu.ph',
    'id_number' => '016-0128',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '5379',
  ),
  139 => 
  array (
    'name' => 'Cyruz Sibug',
    'email' => '23-0203@aldersgate.edu.ph',
    'id_number' => '23-0203',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '9175',
  ),
  140 => 
  array (
    'name' => 'Jerald Labog Solis',
    'email' => '20-10492@aldersgate.edu.ph',
    'id_number' => '20-10492',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '5125',
  ),
  141 => 
  array (
    'name' => 'John Lloyd Ballonico Sumawang',
    'email' => '23-0217@aldersgate.edu.ph',
    'id_number' => '23-0217',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '9485',
  ),
  142 => 
  array (
    'name' => 'Jolas Bondad Tucli',
    'email' => '15-10131@aldersgate.edu.ph',
    'id_number' => '15-10131',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '9968',
  ),
  143 => 
  array (
    'name' => 'Jose Victor Foronda Uy',
    'email' => '017-0104@aldersgate.edu.ph',
    'id_number' => '017-0104',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '6738',
  ),
  144 => 
  array (
    'name' => 'Jameson Galutera Valera',
    'email' => '18-10147@aldersgate.edu.ph',
    'id_number' => '18-10147',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '2410',
  ),
  145 => 
  array (
    'name' => 'Roi Jetzter Cala Villa',
    'email' => '22-10268@aldersgate.edu.ph',
    'id_number' => '22-10268',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '3',
    'section' => 'BSIT-4A',
    'password' => '3981',
  ),
  146 => 
  array (
    'name' => 'Delight Grace Baliwang Yogyog',
    'email' => '23-0403@aldersgate.edu.ph',
    'id_number' => '23-0403',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '3',
    'section' => 'BSIT-3A',
    'password' => '7158',
  ),
  147 => 
  array (
    'name' => 'Albert Acangan',
    'email' => '22-0465@aldersgate.edu.ph',
    'id_number' => '22-0465',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '6262',
  ),
  148 => 
  array (
    'name' => 'Gian Carlo Bautista Anquiliano',
    'email' => '22-0107@aldersgate.edu.ph',
    'id_number' => '22-0107',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '5805',
  ),
  149 => 
  array (
    'name' => 'Renz Cruz Aspiras',
    'email' => '21-10127@aldersgate.edu.ph',
    'id_number' => '21-10127',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '2891',
  ),
  150 => 
  array (
    'name' => 'Cristeta Morales Balunsat',
    'email' => '22-10361@aldersgate.edu.ph',
    'id_number' => '22-10361',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '2115',
  ),
  151 => 
  array (
    'name' => 'Erwin Dumlao Bartolome',
    'email' => '20-10626@aldersgate.edu.ph',
    'id_number' => '20-10626',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '6896',
  ),
  152 => 
  array (
    'name' => 'Gil Goden Keiffer Galasinao **** Bassi',
    'email' => '21-10910@aldersgate.edu.ph',
    'id_number' => '21-10910',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-2A',
    'password' => '2874',
  ),
  153 => 
  array (
    'name' => 'Jr. Omanito Buado, Edwin',
    'email' => '22-0513@aldersgate.edu.ph',
    'id_number' => '22-0513',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '6849',
  ),
  154 => 
  array (
    'name' => 'Ronnie Humiwat Bueno',
    'email' => '22-10213@aldersgate.edu.ph',
    'id_number' => '22-10213',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '5988',
  ),
  155 => 
  array (
    'name' => 'Darlito DELA CRUZ Cabalse',
    'email' => '19-10532@aldersgate.edu.ph',
    'id_number' => '19-10532',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '8319',
  ),
  156 => 
  array (
    'name' => 'Joe Wilson Dulnuan Daulayan',
    'email' => '21-10210@aldersgate.edu.ph',
    'id_number' => '21-10210',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '3015',
  ),
  157 => 
  array (
    'name' => 'Lou Aviane Garcia Doctor',
    'email' => '20-10040@aldersgate.edu.ph',
    'id_number' => '20-10040',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '3830',
  ),
  158 => 
  array (
    'name' => 'Kathlene Claire Hora Feliciano',
    'email' => '22-0072@aldersgate.edu.ph',
    'id_number' => '22-0072',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '7941',
  ),
  159 => 
  array (
    'name' => 'Brix Aila Genchez Fernandez',
    'email' => '22-10267@aldersgate.edu.ph',
    'id_number' => '22-10267',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '7396',
  ),
  160 => 
  array (
    'name' => 'Luke Andrei Lelina Galera',
    'email' => '018-0325@aldersgate.edu.ph',
    'id_number' => '018-0325',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-1A',
    'password' => '6169',
  ),
  161 => 
  array (
    'name' => 'Ian Tristan Landagura',
    'email' => '22-0224@aldersgate.edu.ph',
    'id_number' => '22-0224',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '0946',
  ),
  162 => 
  array (
    'name' => 'Jimbert Martinez Lucero',
    'email' => '22-0420@aldersgate.edu.ph',
    'id_number' => '22-0420',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '7745',
  ),
  163 => 
  array (
    'name' => 'Sierra Pearl Mosquite Pacilan',
    'email' => '21-10379@aldersgate.edu.ph',
    'id_number' => '21-10379',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '8422',
  ),
  164 => 
  array (
    'name' => 'Emil Caranguian Paladin',
    'email' => '22-0182@aldersgate.edu.ph',
    'id_number' => '22-0182',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '1831',
  ),
  165 => 
  array (
    'name' => 'Zyrene Pulista Palawe',
    'email' => '22-0443@aldersgate.edu.ph',
    'id_number' => '22-0443',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '5109',
  ),
  166 => 
  array (
    'name' => 'Jhon Llander Alcaide Pangangaan',
    'email' => '22-0179@aldersgate.edu.ph',
    'id_number' => '22-0179',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '2715',
  ),
  167 => 
  array (
    'name' => 'Nathaniel Fernandez Pelerio',
    'email' => '22-0267@aldersgate.edu.ph',
    'id_number' => '22-0267',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '4576',
  ),
  168 => 
  array (
    'name' => 'Augie Justine Balala Reasonda',
    'email' => '22-0473@aldersgate.edu.ph',
    'id_number' => '22-0473',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '5935',
  ),
  169 => 
  array (
    'name' => 'Irish Vanessa Lozano Reyes',
    'email' => '22-0206@aldersgate.edu.ph',
    'id_number' => '22-0206',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '5341',
  ),
  170 => 
  array (
    'name' => 'Imee Garcia Rodriguez',
    'email' => '22-10488@aldersgate.edu.ph',
    'id_number' => '22-10488',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '2780',
  ),
  171 => 
  array (
    'name' => 'Ervin Klein Valdez Soriano',
    'email' => '21-10873@aldersgate.edu.ph',
    'id_number' => '21-10873',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '6227',
  ),
  172 => 
  array (
    'name' => 'Jaevy Kiss Xenia Garcia Soriano',
    'email' => '18-10106@aldersgate.edu.ph',
    'id_number' => '18-10106',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '0062',
  ),
  173 => 
  array (
    'name' => 'Gerald Ramos Sunga',
    'email' => '22-0183@aldersgate.edu.ph',
    'id_number' => '22-0183',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '0541',
  ),
  174 => 
  array (
    'name' => 'Linuel Jake Galapon Valdez',
    'email' => '22-0255@aldersgate.edu.ph',
    'id_number' => '22-0255',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '2557',
  ),
  175 => 
  array (
    'name' => 'Edmarie Chinelle Cuyat Ventura',
    'email' => '22-10262@aldersgate.edu.ph',
    'id_number' => '22-10262',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'F',
    'year' => '4',
    'section' => 'BSIT-4A',
    'password' => '4009',
  ),
  176 => 
  array (
    'name' => 'Jomar Anquillano Villamor',
    'email' => '22-10483@aldersgate.edu.ph',
    'id_number' => '22-10483',
    'course' => 'BSIT',
    'role' => 'student',
    'sex' => 'M',
    'year' => '4',
    'section' => 'BSIT-2A',
    'password' => '7027',
  ),
);
